# Default values for cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

grafanaDashboard:
  # -- Allows overriding the namespace where the ConfigMap will be created, defaulting to the same one as the Release.
  namespace: ""
  # -- The name of the ConfigMap containing the dashboard.
  configMapName: "cnpg-grafana-dashboard"
  # -- Label that ConfigMaps should have to be loaded as dashboards. DEPRECATED: Use labels instead.
  sidecarLabel: ""
  # -- Label value that ConfigMaps should have to be loaded as dashboards. DEPRECATED: Use labels instead.
  sidecarLabelValue: ""
  # -- Labels that ConfigMaps should have to get configured in Grafana.
  labels:
    grafana_dashboard: "1"
  # -- Annotations that ConfigMaps can have to get configured in Grafana.
  annotations: {}
